name: "Auto-Deploy"

on:
  schedule:
    # Run at 6am on Sunday and Wednesdays
    - cron: '0 6 * * 0,3'

jobs:
  deploy:
    name: 'Auto Deploy'
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.NETLIFY_DEPLOY_HOOK }}
          method: 'POST'

